/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import model.Szemely;

/**
 *
 * @author Pepe
 */
public class SzemelyadatokDialog extends javax.swing.JDialog {

    private Szemely szemely;
    private boolean mentes;
    
    public SzemelyadatokDialog(java.awt.Frame parent, Szemely szemely) {
        super(parent, true);
        initComponents();
        mentes = false;
        this.szemely=szemely;
        setLocationRelativeTo(parent);
        if (szemely==null) {
            setTitle("Új személy felvétele");
        } else {
            setTitle("Személy adatainak módosítása");
            TxtfNev.setText(szemely.getNev());
            TxtfEmail.setText(szemely.getEmail());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtfNev = new javax.swing.JTextField();
        TxtfEmail = new javax.swing.JTextField();
        BTMegsem = new javax.swing.JButton();
        BTOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Név:");

        jLabel2.setText("E-mail:");

        BTMegsem.setText("Mégsem");
        BTMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTMegsemActionPerformed(evt);
            }
        });

        BTOk.setText("OK");
        BTOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BTOk)
                        .addGap(18, 18, 18)
                        .addComponent(BTMegsem, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TxtfNev, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(TxtfEmail))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtfNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTMegsem)
                    .addComponent(BTOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTOkActionPerformed
        mentes = true;
        if (szemely ==null) {
            szemely = new Szemely();
        }
            szemely.setNev(TxtfNev.getText());
            szemely.setEmail(TxtfEmail.getText());
            setVisible(false);
        
    }//GEN-LAST:event_BTOkActionPerformed

    private void BTMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTMegsemActionPerformed
        setVisible(false);
    }//GEN-LAST:event_BTMegsemActionPerformed

    public Szemely getSzemely() {
        return szemely;
    }


    public boolean isMentes() {
        return mentes;
    }


    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTMegsem;
    private javax.swing.JButton BTOk;
    private javax.swing.JTextField TxtfEmail;
    private javax.swing.JTextField TxtfNev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
